### ISSUE TITLE
Dynamically critical css

### ISSUE THREAD

**Issue by approached** [kalfheim/critical-css#2]
Hi,

good package you have created. I would self develop this feature. But your are now done. But one question what i have is.

How i can generate dynamically critical css?
I mean if you have a blog and you create a article. Than you have a new url like this: /blog/my-blog-entry . For this URL me need a now a critical css.

I hope it is clear what i mean.

Thanks

**Comment by kalfheim** [comment]
Hi!

If all blog posts have simliar above-the-fold layouts, I would recommend creating a route alias in the config. Like so:

``` php
'routes' => [
    'blog/generic-post' => 'blog/some-post-that-actually-exists',
],
```

Then reference "blog/generic-post" in Blade, like so: `@criticalCss('blog/generic-post')`

Given a similiar layout for all blog posts, this will most likely do the trick.

Other than that, the functionally to dynamically generate and load critical-path CSS is currently missing. If you have ideas on how this could be implemented in a nice fashion, please feel free to let me know.

Thanks for showing interest in the package! :smiley:

**Comment by approached** [comment]
Ok thanks.

In next time i will create a dynamic critical css.
With queues and event handling.
